# Generated by Django 3.1.4 on 2022-05-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('DNI', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(upload_to='imagenes/')),
                ('residencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_members.ciclo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_members.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('DNI', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(upload_to='imagenes/')),
                ('residencia', models.CharField(max_length=200)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_members.ciclo')),
            ],
        ),
    ]
