# Generated by Django 3.1.4 on 2022-06-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
