# Generated by Django 3.1.4 on 2022-06-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_members', '0002_auto_20220601_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='horas',
            field=models.IntegerField(default=0),
        ),
    ]
