# Generated by Django 3.1.4 on 2022-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_members', '0003_asignatura_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(null=b'I01\n', upload_to='alumnos'),
            preserve_default=b'I01\n',
        ),
    ]
