# Generated by Django 3.1.4 on 2022-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_members', '0005_auto_20220602_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunnos/'),
        ),
    ]
